name: deploy

on:
  push:
    branches:
      - 'main'
env:
  s3_bucket: ${{ secrets.S3_BUCKET }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:headless
      - name: "ECHO AWS"
        run: echo "acct=${{ secrets.AWS_DEV_ACCT }} role=${{ secrets.AWS_ROLE }} bucket=$s3_bucket"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_DEV_ACCT }}:role/${{ secrets.AWS_ROLE }}
          aws-region: us-east-2
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync ./dist/ar-demo s3://$s3_bucket
